---
apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-secrets-config
  namespace: vault
data:
  config.yaml: |
    - path: mediasrv/jellyfin
      data:
        - key: serverID
          length: 32
          special: false
          uppercase: false
        - key: ldapServiceAccountPassword
          length: 32
          special: false
          uppercase: true

    - path: mediasrv/prowlarr
      data:
        - key: apiKey
          length: 32
          special: false
          uppercase: false

    - path: mediasrv/radarr
      data:
        - key: apiKey
          length: 32
          special: false
          uppercase: false

    - path: mediasrv/sabnzbd
      data:
        - key: apiKey
          length: 32
          special: false
          uppercase: false
        - key: nzbKey
          length: 32
          special: false
          uppercase: false

    - path: mediasrv/sonarr
      data:
        - key: apiKey
          length: 32
          special: false
          uppercase: false
---
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secrets
  namespace: vault
spec:
  ttlSecondsAfterFinished: 3600   # Delete 1 hour after finishing
  template:
    metadata:
      name: generate-secrets
    spec:
      securityContext:
        runAsUser: 108200
        runAsGroup: 108200
        fsGroup: 108200
      restartPolicy: Never
      containers:
        - name: apply
          image: registry.gitlab.com/ralgar/vault-generate-secrets:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              value: http://vault:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: vault-root
          volumeMounts:
            - name: generate-secrets-config
              mountPath: /config
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              memory: 250Mi
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      volumes:
        - name: generate-secrets-config
          configMap:
            name: generate-secrets-config
