---
- name: Install system packages for Kolla
  ansible.builtin.dnf:
    name:
      - dbus-daemon
      - dbus-devel
      - git
      - glib2-devel
      - python3-devel
      - libffi-devel
      - gcc
      - openssl-devel
      - python3-libselinux
    state: present
    update_cache: true
  become: true

- name: Initialize Kolla venv with latest 'pip' and 'wheel'
  ansible.builtin.pip:
    name:
      - pip
      - wheel
    state: latest
    virtualenv: "{{ kolla_venv }}"
    virtualenv_command: python -m venv

- name: Set Ansible Python interpreter to Kolla venv
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ kolla_venv }}/bin/python"

- name: Install Kolla venv dependencies
  ansible.builtin.pip:
    name:
      - 'ansible-core>=2.14,<2.16'
      - dbus-python
      - 'openstacksdk==2.1.0'
      - selinux

- name: Install 'kolla-ansible'
  ansible.builtin.pip:
    name: "git+https://opendev.org/openstack/kolla-ansible@stable/{{ openstack_release }}"
  notify: bootstrap
