---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prowlarr-init
  namespace: media-server
data:
  init.sh: |
    #!/bin/sh
    set -xeu

    envsubst < /configmap/config.xml > /config/config.xml

  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>9696</Port>
      <SslPort>6969</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>$PROWLARR__API_KEY</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Prowlarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <PostgresUser>$PROWLARR__POSTGRES_USER</PostgresUser>
      <PostgresPassword>$PROWLARR__POSTGRES_PASSWORD</PostgresPassword>
      <PostgresPort>$PROWLARR__POSTGRES_PORT</PostgresPort>
      <PostgresHost>$PROWLARR__POSTGRES_HOST</PostgresHost>
      <PostgresMainDb>$PROWLARR__POSTGRES_MAIN_DB</PostgresMainDb>
      <PostgresLogDb>$PROWLARR__POSTGRES_LOG_DB</PostgresLogDb>
    </Config>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: prowlarr
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Unsupported for this app."
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: 109696
        runAsGroup: 109030
        fsGroup: 109030
      initContainers:
        - name: init
          image: docker.io/blockstack/envsubst:latest@sha256:d64d7430289a2440d86b68047207d0454a4b67be6afa6600c4df4978d48aecfb
          imagePullPolicy: IfNotPresent
          command: ["/configmap/init.sh"]
          env:
            - name: PROWLARR__API_KEY
              valueFrom: { secretKeyRef: { name: prowlarr-secrets, key: apiKey } }
            - name: PROWLARR__POSTGRES_HOST
              valueFrom: { secretKeyRef: { name: mediadb-pguser-prowlarr, key: host } }
            - name: PROWLARR__POSTGRES_PORT
              valueFrom: { secretKeyRef: { name: mediadb-pguser-prowlarr, key: port } }
            - name: PROWLARR__POSTGRES_USER
              valueFrom: { secretKeyRef: { name: mediadb-pguser-prowlarr, key: user } }
            - name: PROWLARR__POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: mediadb-pguser-prowlarr, key: password } }
            - name: PROWLARR__POSTGRES_MAIN_DB
              value: prowlarr-main
            - name: PROWLARR__POSTGRES_LOG_DB
              value: prowlarr-log
          volumeMounts:
            - name: prowlarr-init
              mountPath: /configmap
            - name: prowlarr-config
              mountPath: /config
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:2.1.5
          imagePullPolicy: IfNotPresent
          ports:
            - name: prowlarr-http
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 2000m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:9696/api/v1/system/status?apiKey=`IFS=\> && while read -d
                \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9696
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 9696
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: prowlarr-init
          configMap:
            name: prowlarr-init
            defaultMode: 0700   # Executable for script
        - name: prowlarr-config
          emptyDir:
            sizeLimit: 128Mi
