---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - descheduler.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - metrics-server.yaml
  - monitoring.yaml
  - snapshot-controller.yaml
  - volsync.yaml
