---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cert-manager.yaml
  - csi-cinder.yaml
  - descheduler.yaml
  - external-dns.yaml
  - ingress-nginx.yaml
  - monitoring.yaml
  - olm.yaml
  - trust-manager.yaml
  - volsync.yaml
