---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-init
  namespace: media-server
data:
  init.sh: |
    #!/bin/sh
    set -xeu

    envsubst < /configmap/config.xml > /config/config.xml

  config.xml: |
    <Config>
      <BindAddress>*</BindAddress>
      <Port>7878</Port>
      <SslPort>9898</SslPort>
      <EnableSsl>False</EnableSsl>
      <LaunchBrowser>False</LaunchBrowser>
      <ApiKey>$RADARR__API_KEY</ApiKey>
      <AuthenticationMethod>None</AuthenticationMethod>
      <AuthenticationRequired>Enabled</AuthenticationRequired>
      <LogLevel>debug</LogLevel>
      <SslCertPath></SslCertPath>
      <SslCertPassword></SslCertPassword>
      <UrlBase></UrlBase>
      <InstanceName>Radarr</InstanceName>
      <UpdateMechanism>Docker</UpdateMechanism>
      <PostgresUser>$RADARR__POSTGRES_USER</PostgresUser>
      <PostgresPassword>$RADARR__POSTGRES_PASSWORD</PostgresPassword>
      <PostgresPort>$RADARR__POSTGRES_PORT</PostgresPort>
      <PostgresHost>$RADARR__POSTGRES_HOST</PostgresHost>
      <PostgresMainDb>$RADARR__POSTGRES_MAIN_DB</PostgresMainDb>
      <PostgresLogDb>$RADARR__POSTGRES_LOG_DB</PostgresLogDb>
    </Config>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: radarr
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Unsupported for this app."
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: 107878
        runAsGroup: 109030
        fsGroup: 109030
        seLinuxOptions:
          level: "s0:c123,c456"
      initContainers:
        - name: init
          image: docker.io/blockstack/envsubst:latest@sha256:d64d7430289a2440d86b68047207d0454a4b67be6afa6600c4df4978d48aecfb
          imagePullPolicy: IfNotPresent
          command: ["/configmap/init.sh"]
          env:
            - name: RADARR__API_KEY
              valueFrom: { secretKeyRef: { name: radarr-secrets, key: apiKey } }
            - name: RADARR__POSTGRES_HOST
              valueFrom: { secretKeyRef: { name: mediadb-pguser-radarr, key: host } }
            - name: RADARR__POSTGRES_PORT
              valueFrom: { secretKeyRef: { name: mediadb-pguser-radarr, key: port } }
            - name: RADARR__POSTGRES_USER
              valueFrom: { secretKeyRef: { name: mediadb-pguser-radarr, key: user } }
            - name: RADARR__POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: mediadb-pguser-radarr, key: password } }
            - name: RADARR__POSTGRES_MAIN_DB
              value: radarr-main
            - name: RADARR__POSTGRES_LOG_DB
              value: radarr-log
          volumeMounts:
            - name: radarr-init
              mountPath: /configmap
            - name: radarr-config
              mountPath: /config
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      containers:
        - name: radarr
          image: ghcr.io/home-operations/radarr:6.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: radarr-http
              containerPort: 7878
              protocol: TCP
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: media
              mountPath: /media
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 2000m
              memory: 500Mi
          livenessProbe:
            exec:
              command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while read -d
                \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
      volumes:
        - name: radarr-init
          configMap:
            name: radarr-init
            defaultMode: 0700   # Executable for script
        - name: radarr-config
          emptyDir:
            sizeLimit: 128Mi
        - name: media
          persistentVolumeClaim:
            claimName: media
